name           = "Getopt-EX-Config"
badges         = [ 'github-actions/test', 'metacpan' ]
module_maker   = "ModuleBuildTiny"
static_install = "auto"

[release]
branch = "main"
do_not_upload_to_cpan = 0

